# The marshalers that turn assigned values into what an attribute reads as and stores.
require "./marshalers/marshaler"
require "./marshalers/string_marshaler"
require "./marshalers/boolean_marshaler"
require "./marshalers/integer_marshaler"
require "./marshalers/float_marshaler"
require "./marshalers/date_marshaler"
require "./marshalers/date_time_marshaler"
require "./marshalers/time_marshaler"
require "./marshalers/epoch_time_marshaler"
require "./marshalers/list_marshaler"
require "./marshalers/map_marshaler"
require "./marshalers/string_set_marshaler"
require "./marshalers/numeric_set_marshaler"
