# The `Aws::DynamoDB` layer: a minimal, typed DynamoDB client owned by this shard.
require "./dynamodb/value"
require "./dynamodb/attribute_value"
require "./dynamodb/errors"
require "./dynamodb/credentials"
require "./dynamodb/config"
require "./dynamodb/types"
require "./dynamodb/operation"
require "./dynamodb/retry"
require "./dynamodb/http"
require "./dynamodb/stub"
require "./dynamodb/paginator"
require "./dynamodb/client"
