# Port of `lib/aws-record.rb` — requires the DynamoDB client layer and then the record layer.
#
# Crystal is mostly order-independent, but macros used by `record/base.cr` must be defined
# before use, so the order below is explicit and intentional.
require "./aws-record/version"
require "./aws-record/dynamodb"
require "./aws-record/record/raw_value"
require "./aws-record/record/time_parsing"
require "./aws-record/record/marshalers"
require "./aws-record/record/errors"
require "./aws-record/record/attribute"
require "./aws-record/record/model_attributes"
require "./aws-record/record/item_data"
require "./aws-record/record/client_configuration"
require "./aws-record/record/base"
require "./aws-record/record/dirty_tracking"
require "./aws-record/record/item_operations"
require "./aws-record/record/item_collection"
require "./aws-record/record/buildable_search"
require "./aws-record/record/query"
require "./aws-record/record/secondary_indexes"
require "./aws-record/record/table_migration"
require "./aws-record/record/table_config"
require "./aws-record/record/batch_write"
require "./aws-record/record/batch_read"
require "./aws-record/record/batch"
require "./aws-record/record/transactions"
